USE IPL;
#Some values in IPL_MATCH was changed. In MATCH_WINNER some values were cahnged which were same as team_ids.

#1.	Show the percentage of wins of each bidder in the order of highest to lowest percentage.

SELECT IBP.BIDDER_ID, BIDDER_NAME,IFNULL(PER_OF_WIN,0) AS PER_OF_WIN FROM IPL_BIDDER_POINTS IBP
LEFT JOIN (SELECT BIDDER_ID, COUNT(*), AVG(NO_OF_BIDS), ROUND((COUNT(*)/AVG(NO_OF_BIDS)),2)*100 AS PER_OF_WIN 
FROM IPL_BIDDER_POINTS NATURAL JOIN IPL_BIDDING_DETAILS WHERE BID_STATUS = 'Won' GROUP BY BIDDER_ID) AS A
ON IBP.BIDDER_ID = A.BIDDER_ID
JOIN IPL_BIDDER_DETAILS IBD ON IBP.BIDDER_ID = IBD.BIDDER_ID
ORDER BY PER_OF_WIN DESC;


#2.	Which teams have got the highest and the lowest no. of bids?

SELECT BID_TEAM, TEAM_NAME, CNT
FROM (SELECT BID_TEAM, COUNT(*) AS CNT FROM IPL_BIDDING_DETAILS GROUP BY BID_TEAM) AS A
JOIN IPL_TEAM IT ON A.BID_TEAM = IT.TEAM_ID
HAVING CNT IN (SELECT MAX(CNT) FROM(SELECT COUNT(*) AS CNT FROM IPL_BIDDING_DETAILS GROUP BY BID_TEAM) AS B)
OR CNT IN (SELECT MIN(CNT) FROM(SELECT COUNT(*) AS CNT FROM IPL_BIDDING_DETAILS GROUP BY BID_TEAM) AS B)
ORDER BY CNT DESC;



#3.	In a given stadium, what is the percentage of wins by a team which had won the toss?

SELECT C.STADIUM_ID, STADIUM_NAME, WINNER_TEAM, TEAM_NAME, TEAM_WIN_COUNT, ST_COUNT, ROUND((TEAM_WIN_COUNT/ST_COUNT)*100,2) AS PERC_WIN
FROM (SELECT STADIUM_ID, WINNER_TEAM, COUNT(*) AS TEAM_WIN_COUNT
FROM 
(SELECT A.MATCH_ID, TEAM_ID1, TEAM_ID2, TOSS_WINNER, MATCH_WINNER, STADIUM_ID,
(CASE
		WHEN TOSS_WINNER = MATCH_WINNER THEN TOSS_WINNER_TEAM
        ELSE 0
END) AS WINNER_TEAM
FROM (SELECT MATCH_ID, TEAM_ID1, TEAM_ID2, TOSS_WINNER, MATCH_WINNER,
(CASE 
	WHEN TOSS_WINNER = 1 THEN TEAM_ID1
    WHEN TOSS_WINNER = 2 THEN TEAM_ID2
END) AS TOSS_WINNER_TEAM
FROM IPL_MATCH) AS A
JOIN IPL_MATCH_SCHEDULE IMS ON A.MATCH_ID = IMS.MATCH_ID) AS B
GROUP BY STADIUM_ID, WINNER_TEAM) AS C
JOIN (SELECT STADIUM_ID, COUNT(*) AS ST_COUNT
FROM 
(SELECT A.MATCH_ID, TEAM_ID1, TEAM_ID2, TOSS_WINNER, MATCH_WINNER, STADIUM_ID,
(CASE
		WHEN TOSS_WINNER = MATCH_WINNER THEN TOSS_WINNER_TEAM
        ELSE 0
END) AS WINNER_TEAM
FROM (SELECT MATCH_ID, TEAM_ID1, TEAM_ID2, TOSS_WINNER, MATCH_WINNER,
(CASE 
	WHEN TOSS_WINNER = 1 THEN TEAM_ID1
    WHEN TOSS_WINNER = 2 THEN TEAM_ID2
END) AS TOSS_WINNER_TEAM
FROM IPL_MATCH) AS A
JOIN IPL_MATCH_SCHEDULE IMS ON A.MATCH_ID = IMS.MATCH_ID) AS B
GROUP BY STADIUM_ID) AS D
ON C.STADIUM_ID = D.STADIUM_ID
JOIN IPL_STADIUM IST ON C.STADIUM_ID = IST.STADIUM_ID
JOIN IPL_TEAM IT ON C.WINNER_TEAM = IT.TEAM_ID
WHERE WINNER_TEAM!=0
ORDER BY C.STADIUM_ID,WINNER_TEAM;



#4.	What is the total no. of bids placed on the team that has won highest no. of matches?

SELECT TEAM_NAME, COUNT(*) AS NO_OF_BIDS
FROM IPL_BIDDING_DETAILS IBD
JOIN IPL_TEAM IT ON IBD.BID_TEAM = IT.TEAM_ID
WHERE BID_TEAM = (SELECT MATCH_WINNER_TEAM
FROM (SELECT MATCH_ID, TEAM_ID1, TEAM_ID2, TOSS_WINNER, MATCH_WINNER,
(CASE 
	WHEN MATCH_WINNER = 1 THEN TEAM_ID1
    WHEN MATCH_WINNER = 2 THEN TEAM_ID2
END) AS MATCH_WINNER_TEAM
FROM IPL_MATCH) AS A
GROUP BY MATCH_WINNER_TEAM
ORDER BY COUNT(*) DESC
LIMIT 1)
GROUP BY BID_TEAM;



#5.	From the current team standings, if a bidder places a bid on which of the teams, there is a possibility 
#of (s)he winning the highest no. of points – in simple words, identify the team which has the highest jump 
#in its total points (in terms of percentage) from the previous year to current year.

SELECT A.TEAM_ID, TEAM_NAME, A.TOTAL_POINTS, B.TOTAL_POINTS, ROUND(((B.TOTAL_POINTS-A.TOTAL_POINTS)/(A.TOTAL_POINTS))*100,2) AS DIFF_PERC
FROM (SELECT * FROM IPL_TEAM_STANDINGS
WHERE TOURNMT_ID = 2017) AS A
JOIN (SELECT * FROM IPL_TEAM_STANDINGS
WHERE TOURNMT_ID = 2018) AS B
ON A.TEAM_ID = B.TEAM_ID
JOIN IPL_TEAM IT ON A.TEAM_ID = IT.TEAM_ID
ORDER BY DIFF_PERC DESC
LIMIT 1;


